apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: agent-marketplace
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: kmcallo/agent-marketplace-api:latest
          command: ["python", "-m", "alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: agent-marketplace-secrets
                  key: DATABASE_URL
      restartPolicy: OnFailure
  backoffLimit: 3
