"""Core module for cross-cutting concerns."""

from agent_marketplace_api.core.metrics import (
    AGENT_DOWNLOADS_TOTAL,
    AGENT_UPLOADS_TOTAL,
    AGENTS_GAUGE,
    HTTP_REQUEST_DURATION_SECONDS,
    HTTP_REQUESTS_TOTAL,
    PENDING_VALIDATIONS_GAUGE,
    REVIEWS_TOTAL,
    STARS_TOTAL,
    USERS_GAUGE,
    VALIDATION_DURATION_SECONDS,
    MetricsMiddleware,
    get_metrics,
    track_agent_download,
    track_agent_upload,
    track_review,
    track_star,
    track_validation,
    update_agent_gauge,
    update_pending_validations_gauge,
    update_user_gauge,
)

__all__ = [
    "AGENT_DOWNLOADS_TOTAL",
    "AGENT_UPLOADS_TOTAL",
    "AGENTS_GAUGE",
    "HTTP_REQUEST_DURATION_SECONDS",
    "HTTP_REQUESTS_TOTAL",
    "MetricsMiddleware",
    "PENDING_VALIDATIONS_GAUGE",
    "REVIEWS_TOTAL",
    "STARS_TOTAL",
    "USERS_GAUGE",
    "VALIDATION_DURATION_SECONDS",
    "get_metrics",
    "track_agent_download",
    "track_agent_upload",
    "track_review",
    "track_star",
    "track_validation",
    "update_agent_gauge",
    "update_pending_validations_gauge",
    "update_user_gauge",
]
